### ISSUE TITLE
Install NMDC EDGE web app on a Jetstream2 VM

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/nmdc-edge#112]
Install all software necessary to run NMDC-EDGE platform: Node, ExpressJS, MongoDB, Nginx

**Comment by mflynn-lanl** [comment]
Can try out nmdc-edge website docker image

**Comment by eecavanna** [comment]
So far, I've:
- Created a VM successfully via Exosphere
- Accessed its shell via SSH (using an SSH key I registered via the Exosphere UI)
- Run a Docker container on the VM (an off-the-shelf Nginx image from Docker Hub)
- Accessed the VM/container-hosted Nginx welcome page from a web browser on my local machine
- Deleted the VM

Next up (next time I work on this):
- Set up Nginx (or similar) as a reverse proxy (either as a container or directly on the VM)
- Create a self-signed SSL certificate and configure Nginx to use it
- Update Cloudflare to direct traffic from the EDGE development hostname to this reverse proxy
- Confirm I can access the Nginx welcome page via HTTPS (Cloudflare would be providing the user-facing SSL certificate in that scenario)

**Comment by julianpistorius** [comment]
This is totally unsolicited advice, but in case you're interested we're currently writing a tutorial for Jetstream2 for serving websites securely:

https://gitlab.com/jetstream-cloud/docs/-/merge_requests/86

Instead of Nginx I proposed that we use [Caddy](https://caddyserver.com/) - because it is so easy and takes care of renewing certificates. You can still put Nginx behind Caddy if you depend on Nginx rules or other specific behavior.

**Comment by gitname** [comment]
Thanks, @julianpistorius. I'm out of the office today and will be back in on Monday (I'll be out next Thursday and Friday also).

I don't have any objections to using Caddy. I had planned on using Nginx only because (based on a past conversation with one of the developers of the NMDC EDGE web application) I'm under the impression that that's what the current production NMDC EDGE instance happens to use, and I thought it might provide a common point of reference in future conversations with them. I'll check out that tutorial you linked to once I'm back in the office.

**Comment by eecavanna** [comment]
(Oops... sorry about the double comment. I accidentally posted the first one—which I've since deleted—from my personal account instead of work account.)

**Comment by ssarrafan** [comment]
@eecavanna are you still working on this?  next sprint or backlog?

**Comment by eecavanna** [comment]
I'm still working on it. I'll move it to the next sprint.

**Comment by eecavanna** [comment]
This is done.

In addition, the repo contains a `docker-compose.prod.yml` file that can be used to facilitate subsequent deployments/redeployments. There is also a PR (#162, ready for review) introducing a GitHub Actions workflow that will build and publish updated container images of the web app, to GitHub Container Registry.

I will create a new issue about configuring the web app to communicate with the Cromwell web server.
