### ISSUE TITLE
Assign version numbers to NMDC EDGE releases/updates

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-edge#85]
Currently there is no clear way to track versions and updates in NMDC edge. It would be useful to have tagged releases and versions. This would also help in quarterly reports and updates.

**Comment by eecavanna** [comment]
Here's what I propose:
- On server side: 
  - Provide an HTTP endpoint (e.g. `/version`, `/meta/version`, or similar) which responds with the application version
- On client side:
  - Low-hanging fruit: `console.log()` the version number when the client starts running
  - Longer term: Display the version number on the web UI (e.g. in the footer)

**Comment by ljohnson09** [comment]
Also a beta testing comment - people wanted to know for citation purposes what version numbers they are using

**Comment by eecavanna** [comment]
As of version https://github.com/microbiomedata/nmdc-edge/releases/tag/v0.1.0-alpha.3, the Express.js app has an endpoint — `/api/version` — that returns the version identifier of the app. That is shown in action in the following screenshot:

![image](https://github.com/microbiomedata/nmdc-edge/assets/134325062/a0a3b37f-74d5-4d8a-b239-8572c11940de)

I will open a separate issue about showing this version identifier on the web UI, so that it can more easily be used for citation purposes.
